### ISSUE TITLE
join to organization

### ISSUE THREAD

**Issue by Arhell** [volcano-sh/community#18]
I want to fix bugs, UI , accessibility and more on the site.
PRs:
https://github.com/volcano-sh/website/pull/134
https://github.com/volcano-sh/website/pull/128
https://github.com/volcano-sh/website/pull/130
https://github.com/volcano-sh/website/pull/132
cc @Thor-wl

**Comment by k82cn** [comment]
Already sent the invitation :)

**Comment by Thor-wl** [comment]
Thanks for your contribution! Welcome to Volcano Community!
/lgmt
