### ISSUE TITLE
Donate BoCloud/JobFlow to volcano-sh in order to scheduling of job

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/community#19]
## Background

At present, volcano does not have the ability to orchestrate vcjob natively. In this scenario, it is recommended to use argo. However, there are many problems in the process of using argo, so we established the jobflow project to focus on the orchestration and scheduling of vcjob.

## Project Brief Introduction

Volcano is an CNCF sandbox project aiming for running  tranditional batch jobs on Kubernetes. It abstracts those batch jobs  into an CRD called VCJob and has an excellet scheduler to imporve  resource utilization. However, to solve an real-world issue, we need many VCJobs to cooperate each other and orchestrate them mannualy or by another Job  Orchestruating Platrom to get the job done finally.We present an new way of orchestruing VCJobs called JobFlow. We proposed two concepts to  running multiple batch jobs automatically named JobTemplate and JobFlow  so end users can easily declare their jobs and run them using complex  controlling primitives, for example, sequential or parallel executing,  if-then-else statement, switch-case statement, loop executing and so on.

JobFlow helps migrating AI, BigData, HPC workloads to the  cloudnative world. Though there are already some workload flow engines,  they are not designed for batch job workloads. Those jobs typically have a complex running dependencies and take long time to run, for example  days or weeks. JobFlow helps the end users to declaire their jobs as an  jobTemplate and then reuse them accordingly. Also, JobFlow  orchestruating those jobs using complex controlling primitives and lanch those jobs automatically. This can significantly reduce the time  consumption of an complex job and improve resource utilization. Finally, JobFlow is not an generally purposed workflow engine, it knows the  details of VCJobs. End user can have a better understanding of their  jobs, for example, job's running state, beginning and ending timestamps, the next jobs to run, pod-failure-ratio and so on.

## Founder Introduction

@zhoumingcheng  R&D Engineer @BoCloud
@HecarimV            R&D Engineer @BoCloud
@hwdef                  R&D Engineer @BoCloud
@ZhangZhenhua   Architect @BoCloud
@sssl93 R&D         Director @BoCloud

## License

Apache-2.0 License

## Project Link

https://github.com/BoCloud/JobFlow

**Comment by Thor-wl** [comment]
Great! Thanks for the contribution. I'm glad to under the resposibility of Sponsor to push the process.
/assign

**Comment by hwdef** [comment]
Q & A

**Q1: What's the difference between Argo and JobFlow?**

Argo workflow is a general-purpose workflow orchestration engine. It has powerful functions, but doesn't quite 'understand' Volcano. Argo cannot perceive job resource information in volcano, nor can it perceive the status of pods in vcjob. Jobflow is a job flow orchestration tool specially designed for volcano. It is more closely integrated with volcano, and can perceive various information of the job, and on this basis, the scheduling can be optimized and more fine-grained control. In addition, jobflow is actually more concise and lightweight than argo in deployment and use. 

**Q2: What are the resource management strategies for jobflow?**

Currently we do not have this functionality, we can have more discussions in the community about adding this feature, If the community decides to add this feature, We can bring plug-in functions to jobflow scheduling, such as support for jobflow-level gang scheduling, resource reservation, and more. 

**Q3: Is there some consideration for AI scenario?**

We discussed this at our community meeting and I thought it was a good idea. We will add the checkpoint mechanism and retry mechanism of the job. When there are a large number of vcjobs in the jobflow, if a vcjob fails, the jobflow can be automatically rerun from this job.

**Comment by Thor-wl** [comment]
Explanation Meeting Statement:   https://www.bilibili.com/video/BV1Lm4y1R7BS?spm_id_from=333.999.0.0

**Comment by kevin-wangzefeng** [comment]
/approve
Thanks.

**Comment by Thor-wl** [comment]
@hwdef Congratulations! According to [subject-creation](https://github.com/volcano-sh/community/blob/master/subproject-creation.md), the vote from approvers are 6, which has meet the demand. Pls finish the check listed in the appendix and submit the code. Thank you!

**Comment by hwdef** [comment]
@Thor-wl 
I see, I'll submit a merged PR after adding some last remaining test code.
Thanks to all community members!

**Comment by hwdef** [comment]
@william-wang @k82cn @kevin-wangzefeng @william-wang @wpeng102 @shinytang6 

I have completed all the items in the donation self-check list, and then proceed to the merge step. There are three options for merging the jobflow code into volcano:
1. Create a new repo under the volcano-sh organization and move the jobflow code over there
2. Move the jobflow code to volcano/cmd
3. Move the code of jobflow to the controller component of volcano and integrate with volcano

Which of these three methods is better? Please give your opinion. Thanks!

**Comment by k82cn** [comment]
Prefer the third one: "Move the code of jobflow to the controller component of volcano" :)

**Comment by william-wang** [comment]
@hwdef Prefer the option 3. Thanks.

**Comment by hwdef** [comment]
Based on the current vote, I think we can move forward with option three.
Let's start with the merging of APIs.
Please review this PR.^.^
https://github.com/volcano-sh/apis/pull/67

**Comment by hwdef** [comment]
complete
