### ISSUE TITLE
Request to be an approver of Volcano community

### ISSUE THREAD

**Issue by huone1** [volcano-sh/community#25]
I'm requesting to be an Approver of Volcano community.
I've been a longtime contributor to the volcano community in 2021 and actively contributing to code and review

- develop the feature **NUMA-Aware scheduling**. include a plugin **numa-aware** and a daemonSet [resource-exporter ](https://github.com/volcano-sh/resource-exporter)
 - develop the feature **multi-volcano-schedulers** [#1576](https://github.com/volcano-sh/volcano/pull/1576) 、 [#1565](https://github.com/volcano-sh/volcano/pull/1565)
 -  submit the commit 40+ and Top 10 overall community contribution

Hope bring more improvements for Volcano in the future

**Comment by Thor-wl** [comment]
Thanks for your critical contribution! 
/lgtm

**Comment by william-wang** [comment]
Thanks for your active contribution :)
/lgtm

**Comment by k82cn** [comment]
Thanks very much for your contribution!

Currently, we're builing sig/wg in Volcano; prefer to get more feedback/comments from related co-chairs for your application :)
