### ISSUE TITLE
Request to be an member of Volcano community

### ISSUE THREAD

**Issue by lucming** [volcano-sh/community#27]
Hi, members of Volcano community. I'm requesting to be a member of Volcano community.
Here are some of my contributions:
https://github.com/volcano-sh/volcano/pull/2275
https://github.com/volcano-sh/volcano/pull/2316

**Comment by Thor-wl** [comment]
Thanks for your contribution! Welcome to Volcano community!
/lgtm

**Comment by hwdef** [comment]
/lgtm
welcome!

**Comment by wpeng102** [comment]
/lgtm
Welcome!

**Comment by william-wang** [comment]
+1 
Thanks for the contribution, Welcome to Volcano family :)

**Comment by shinytang6** [comment]
+1
/approve

**Comment by kevin-wangzefeng** [comment]
Invited, please visit https://github.com/volcano-sh to accept the invitation.
