### ISSUE TITLE
Request to be an member of Volcano community

### ISSUE THREAD

**Issue by elinx** [volcano-sh/community#28]
I've learnt a lot from the community last several monthes and made a few improvements by fixing some bugs like volcano-sh/volcano#1981 volcano-sh/volcano#2216 and volcano-sh/volcano#2225, hopely I could join as a member of this raplidy growing community and do more contribution in the future.

**Comment by Thor-wl** [comment]
Thanks for your contribution! Welcome to Volcano community!
/lgtm

**Comment by hwdef** [comment]
/lgtm
Welcome!

**Comment by wpeng102** [comment]
/lgtm
Welcome!

**Comment by william-wang** [comment]
+1
Thanks for the contribution, Welcome to Volcano family :)

**Comment by shinytang6** [comment]
+1
/approve

**Comment by kevin-wangzefeng** [comment]
Invited, please visit https://github.com/volcano-sh to accept the invitation.
