### ISSUE TITLE
Request to be an member of Volcano community

### ISSUE THREAD

**Issue by flyhighzy** [volcano-sh/community#29]
Hi, members of Volcano community. I'm requesting to be a member of Volcano community.
Here are some of my contributions:
[volcano-sh/volcano#2149](https://github.com/volcano-sh/volcano/pull/2149)
[volcano-sh/apis#68](https://github.com/volcano-sh/apis/pull/68)
[volcano-sh/apis#82](https://github.com/volcano-sh/apis/pull/82)

**Comment by william-wang** [comment]
Thanks for your contribution. Welcome to Volcano community.

**Comment by Thor-wl** [comment]
Great!
/lgtm

**Comment by shinytang6** [comment]
+1
/approve

**Comment by kevin-wangzefeng** [comment]
Invited, please visit https://github.com/volcano-sh to accept the invitation.
