### ISSUE TITLE
Request to be an member of Volcano community

### ISSUE THREAD

**Issue by waiterQ** [volcano-sh/community#30]
hi, members of Volcano community. i believe volcano is a bigdata-training advanced scheduler in k8s, i had learnt a lot from it and community, im glad to give a hand to someone help-need with my learnt. Here are some of my contributions:
[volcano-sh/volcano#2260](https://github.com/volcano-sh/volcano/pull/2260)
(WIP)[issues#2337](https://github.com/volcano-sh/volcano/issues/2337)
(WIP)[issues#2282](https://github.com/volcano-sh/volcano/issues/2282)
i hope can join as a member of this thriving community and contribute more, gain more, help more in the future.

**Comment by Thor-wl** [comment]
Thanks for your contribution! Welcome to Volcano community!
/lgtm

**Comment by shinytang6** [comment]
+1
/approve

**Comment by kevin-wangzefeng** [comment]
Invited, please visit https://github.com/volcano-sh to accept the invitation.
