### ISSUE TITLE
Request to be a member of Volcano community.

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/community#35]
Hello, members of Volcano community. Since 2019, I've learned a lot from Volcano community about Kubernetes scheduling, and now I hope to join Volcano community and contribute more.

My contributions mainly focused on command line tools, plugin development, and scheduler architecture enhancement. The detailed PRs were as follows:

## Command Line Tool Enhancement
1. https://github.com/volcano-sh/volcano/pull/542
2. https://github.com/volcano-sh/volcano/pull/591
3. https://github.com/volcano-sh/volcano/pull/622
4. https://github.com/volcano-sh/volcano/pull/656
5. https://github.com/volcano-sh/volcano/pull/666
6. https://github.com/volcano-sh/volcano/pull/668

## Scheduler Architecture Enhancement
1. https://github.com/volcano-sh/volcano/pull/785
2. https://github.com/volcano-sh/volcano/pull/790
3. https://github.com/volcano-sh/volcano/pull/1961

## Plugin Development
1. https://github.com/volcano-sh/volcano/pull/1298
2. https://github.com/volcano-sh/volcano/pull/1303
3. https://github.com/volcano-sh/volcano/pull/1324
4. https://github.com/volcano-sh/volcano/pull/1353
5. https://github.com/volcano-sh/volcano/pull/2458
6. https://github.com/volcano-sh/volcano/pull/2480

## Some Other contributions
1. https://github.com/volcano-sh/volcano/pull/1069
2. https://github.com/volcano-sh/volcano/pull/2463

**Comment by william-wang** [comment]
/approve
Thanks for your contributions. Welcome to Volcano famaliy :)

**Comment by hzxuzhonghu** [comment]
+1 welcome

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/volcano-sh to join.
