### ISSUE TITLE
Request to be a member of Volcano community

### ISSUE THREAD

**Issue by wangyang0616** [volcano-sh/community#36]
Hello, members of Volcano community. In the past few months, I have learned a lot about scheduling in the Volcano community. I hope to join the community and contribute more.

My contributions are as follows:

1. [volcano-sh/apis: Volcano adapts to the k8s v1.25 `#93`](https://github.com/volcano-sh/apis/pull/93)
2. [volcano-sh/volcano: Volcano adapts to the k8s v1.25 `#2533`](https://github.com/volcano-sh/volcano/pull/2533)
4. [Add node image information to the cache of the scheduler. `#2593`](https://github.com/volcano-sh/volcano/pull/2593)
5. [By default, the preemption function of gang and drf is turned off `#2613`](https://github.com/volcano-sh/volcano/pull/2613)
6. [The referenced Volcano API version is updated to 1.7 `#2618`](https://github.com/volcano-sh/volcano/pull/2618)
7. [Use the namespace configuration in kubeconfig `#2596`](https://github.com/volcano-sh/volcano/pull/2596)

**Comment by william-wang** [comment]
/lgtm

Thanks for your contribution. Welcome to Volcano big family :)

**Comment by hzxuzhonghu** [comment]
+1 welcome

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/volcano-sh to join.
