### ISSUE TITLE
Request to be a member of Volcano community

### ISSUE THREAD

**Issue by archlitchi** [volcano-sh/community#37]
Hello, members of Volcano community. In the past several months, I have been working on developing device-sharing policy in volcano, I hope to provide volcano the ability to share third-party devices(GPU,FPGA,NPU,etc) efficiently and stablely. I hope to join the community and contribute more.

My contributions are as follows:
1. [add node lock mechanism to support multiple pods/containers with the same ammount of request #2550](https://github.com/volcano-sh/volcano/pull/2550)
2. [add node lock mechanism to support multiple pods/containers with the same ammount of request(device-plugin part) #30](https://github.com/volcano-sh/devices/pull/30)
3. [rework device sharing in volcano #2643](https://github.com/volcano-sh/volcano/pull/2643)

**Comment by william-wang** [comment]
Thanks for your contribution. Welcome to Volcano big family :)
/lgtm

**Comment by Thor-wl** [comment]
Welcome to the community!
/lgtm

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/volcano-sh to accept and join.

**Comment by Thor-wl** [comment]
Since @archlitchi has accpet the invitation. Close the issue.
/close
