### ISSUE TITLE
Request to join the Volcano community

### ISSUE THREAD

**Issue by Shoothzj** [volcano-sh/community#38]
Hi volcano folks, I'm a contributor currently focusing on reschedule and iot, I'd like to join the volcano community for further contributions.

Following the [requirements](https://github.com/volcano-sh/volcano/blob/master/community-membership.md#member)

See my PR in this link [PRs](https://github.com/volcano-sh/volcano/pulls?q=is%3Apr+author%3Ashoothzj)

Hope to be sponsored by your guys. @william-wang @Thor-wl @hzxuzhonghu @kevin-wangzefeng @shinytang6  @wangyang0616

**Comment by hzxuzhonghu** [comment]
+1 thanks for your contributions

**Comment by Thor-wl** [comment]
+1
/lgtm

**Comment by wangyang0616** [comment]
+1 thanks for your contributions
