### ISSUE TITLE
Request to be an Reviewer of Volcano community

### ISSUE THREAD

**Issue by wangyang0616** [volcano-sh/community#41]
I'm requesting to be an reviewer of Volcano community.

My major contributions are scheduling feature development, core issue fixing, and CI project maintenance. I have participated in fixing 20 [issues](https://github.com/volcano-sh/volcano/issues?q=is%3Aissue+author%3Awangyang0616+is%3Aclosed) and [reviewed ](https://github.com/volcano-sh/volcano/pulls?q=is%3Apr+reviewed-by%3Awangyang0616+is%3Aclosed+)30 PRs. The detailed contributions are as follows:

**Feature：**
- [Volcano adapts to the k8s v1.25 #2533](https://github.com/volcano-sh/volcano/pull/2533)
- [Volcano automatically releases the corresponding helm charts package #2823](https://github.com/volcano-sh/volcano/pull/2823)
- [Refactor PredicateFn for allocate and preempt actions #2916](https://github.com/volcano-sh/volcano/pull/2916)
- [Add jobflow-related content to Volcano automatic installation and deployment #2936](https://github.com/volcano-sh/volcano/pull/2936)

**Bugfix:** 
- [Add node image information to the cache of the scheduler. #2593](https://github.com/volcano-sh/volcano/pull/2593)
- [By default, the preemption function of gang and drf is turned off #2613](https://github.com/volcano-sh/volcano/pull/2613)
- [fix: deployment and pod, high priority cannot preempt low priority resources #2630](https://github.com/volcano-sh/volcano/pull/2630)
- [The preemption logic is only controlled by jobMinavailable in the gang plugin #2634](https://github.com/volcano-sh/volcano/pull/2634)
- [The allocate phase only updates the podgroup in the pending state to the inqueue state #2658](https://github.com/volcano-sh/volcano/pull/2658)
- [Add rescheduling related location logs #2698](https://github.com/volcano-sh/volcano/pull/2698)
- [imagePullPolicy changed from IfNotPresent to Always #2721](https://github.com/volcano-sh/volcano/pull/2721)
- [Fix the problem that the program crashes if the gpuShare Devices is empty #2751](https://github.com/volcano-sh/volcano/pull/2751)
- [Added version compatibility instructions for Volcano and K8s #2770](https://github.com/volcano-sh/volcano/pull/2770)
- [fix: high priority job of two tasks cannot preempt low priority job of one task #2775](https://github.com/volcano-sh/volcano/pull/2775)
- [fix: UT works fine and covers #2811](https://github.com/volcano-sh/volcano/pull/2811)
- [Fix: the admission-init error is reported when Volcano is installed repeatedly. #2834](https://github.com/volcano-sh/volcano/pull/2834)
- [Fix: the pod pipeline status is incompatible with autoscaler capacity expansion #3001](https://github.com/volcano-sh/volcano/pull/3001)

**CI Engineering Maintenance：**
- [Fix the problem exposed by golangci-lint static check #2645](https://github.com/volcano-sh/volcano/pull/2645)
- [Optimize e2e runtime: reduce pytorch-plugin image download time #2691](https://github.com/volcano-sh/volcano/pull/2691)
- [ginkgo upgraded from v2.3.0 to v2.8.3 #2719](https://github.com/volcano-sh/volcano/pull/2719)
- [Use the latest example-mpi mirror #2722](https://github.com/volcano-sh/volcano/pull/2722)
- [Fix trunk CI grafana.yaml file parsing error #2728](https://github.com/volcano-sh/volcano/pull/2728)
- [Upgrade the ubuntu version to fix the problem that CI cannot run #2769](https://github.com/volcano-sh/volcano/pull/2769)
- [Use cases for blocking CI probabilistic failures #2780](https://github.com/volcano-sh/volcano/pull/2780)
- [verify-golangci-lint fails to run in CI, code merging is not allowed #2808](https://github.com/volcano-sh/volcano/pull/2808)
- [fix goimport check error #2849](https://github.com/volcano-sh/volcano/pull/2849)
- [Let the make manifest work properly #2917](https://github.com/volcano-sh/volcano/pull/2917)
- [Upgrade the setup-go and checkout versions in the action && fix Spark CI #2938](https://github.com/volcano-sh/volcano/pull/2938)

**Process：**
- [Supports the collection of average indicator data for multiple time periods #2706](https://github.com/volcano-sh/volcano/pull/2706)
- [Extend the default timeout for stale #2778](https://github.com/volcano-sh/volcano/pull/2778)
- [sed syntax is compatible with linux and darwin systems #2848](https://github.com/volcano-sh/volcano/pull/2848)
- [Automatically clean up and install Volcano's initialization job #2855](https://github.com/volcano-sh/volcano/pull/2855)
- [resourcequota supports flexible jobs #2899](https://github.com/volcano-sh/volcano/pull/2899)

**Comment by william-wang** [comment]
Thanks for your great contribution :)
+1

**Comment by hwdef** [comment]
+1
I've been looking forward to this day for a long time.
Thanks for your contribution.

**Comment by jiangkaihua** [comment]
Thanks for your great contribution : )
+1

**Comment by Thor-wl** [comment]
+1
Best regards to you.
