### ISSUE TITLE
Request to be a member of Volcano community

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/community#42]
Hello, members of Volcano community. In the past year, I learned about the framework and design details of voclcano, and contributed some features and bug fixes in the community. Volcano is a very popular project in batch scheduling, I hope to become a member of the community and make more contribution.

Here are main pull requests merged in Volcano community:

- [Add podTopologySpread plugin](https://github.com/volcano-sh/volcano/pull/2487)
- [Ensure deletion of pods is handled ](https://github.com/volcano-sh/volcano/pull/2784)
- [abstract Bind() param to kubernetes.Interface ](https://github.com/volcano-sh/volcano/pull/2869)
- [fix PodToplogySpread plugin violates maxSkew](https://github.com/volcano-sh/volcano/pull/2929)
- [remove node out of sync state](https://github.com/volcano-sh/volcano/pull/2998)

**Comment by wangyang0616** [comment]
+1 thanks for your contributions.

**Comment by Thor-wl** [comment]
+1
Welcome to Volcano community!
