### ISSUE TITLE
Request to be a member of Volcano community

### ISSUE THREAD

**Issue by guoqinwill** [volcano-sh/community#52]
Hello, members of Volcano community. I've learnt a lot from the community last several monthes and made a few improvements by fixing some bugs，and now I hope to join Volcano community and contribute more.

Here are main pull requests merged in Volcano community:

https://github.com/volcano-sh/volcano/pull/3295
https://github.com/volcano-sh/volcano/pull/3352
https://github.com/volcano-sh/volcano/pull/3347
https://github.com/volcano-sh/volcano/pull/3375
https://github.com/volcano-sh/volcano/pull/3213

**Comment by k82cn** [comment]
/lgtm

thanks very much :)

**Comment by wangyang0616** [comment]
+1
Welcome to Volcano community!

**Comment by Thor-wl** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Thanks for your contributions and welcome onboard.
Invitation sent, please visit https://github.com/volcano-sh to confirm and join.
