### ISSUE TITLE
Request to be a member of Volcano community

### ISSUE THREAD

**Issue by googs1025** [volcano-sh/community#54]
Hello,  Volcano community! Over the past few months, I have learned a great deal from the community and have made several improvements by submitting some PR. Now, I am eager to become a part of the Volcano community and contribute even more.

Here are the PR that have been merged in the Volcano community: 

ongoing: 
https://github.com/volcano-sh/volcano/pull/3482
https://github.com/volcano-sh/volcano/pull/3422
https://github.com/volcano-sh/volcano/pull/3412
https://github.com/volcano-sh/volcano/pull/3486
https://github.com/volcano-sh/volcano/pull/3500
https://github.com/volcano-sh/volcano/pull/3508

merged: 
https://github.com/volcano-sh/volcano/pull/3494
https://github.com/volcano-sh/volcano/pull/3467
https://github.com/volcano-sh/volcano/pull/3453
https://github.com/volcano-sh/volcano/pull/3452
https://github.com/volcano-sh/volcano/pull/3450
https://github.com/volcano-sh/volcano/pull/3447
https://github.com/volcano-sh/volcano/pull/3410
https://github.com/volcano-sh/volcano/pull/3400
https://github.com/volcano-sh/volcano/pull/3377
https://github.com/volcano-sh/volcano/pull/3390
https://github.com/volcano-sh/volcano/pull/3383

**Comment by Monokaix** [comment]
Thanks for your contribution and welcome！
+1

**Comment by Monokaix** [comment]
cc @kevin-wangzefeng

**Comment by lowang-bh** [comment]
+1
welcome!

**Comment by kevin-wangzefeng** [comment]
Thanks for your contributions and welcome onboard.
Invitation sent, please visit https://github.com/volcano-sh to confirm and join.

**Comment by googs1025** [comment]
Thank! I will close this issue
