### ISSUE TITLE
REQUEST: <Add> repo for multi-cluster scheduling

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/community#59]
Name for new repository:
volcano-global

Who should have admin access(subproject owners)?
@kevin-wangzefeng
@william-wang

Who should have write access?
@william-wang
@kevin-wangzefeng
@lowang-bh
@hwdef
@Monokaix

Who should be listed as approvers and reviewers in OWNERS?
approvers:
@william-wang
@kevin-wangzefeng
@Monokaix
reviewers:
@william-wang
@kevin-wangzefeng
@lowang-bh
@hwdef
@Monokaix

What should the repo description be?
Repository for federation scheduler for multi-cluster

Additional context for request.
This repository was created previously with the name `federation`, We'd like to replace the repo name from `federation` to `volcano-global`.  We had many discussion about multi-cluster scheduling previously. This year we are designing and implementing this feature in LFX project. Right now we'd like to contribute it to community.

https://github.com/volcano-sh/federation

related issue:
https://github.com/volcano-sh/volcano/issues/3310

**Comment by Monokaix** [comment]
+1
That's a great feature!

**Comment by Murphylu1993** [comment]
glad to see it

**Comment by lowang-bh** [comment]
+1

**Comment by hwdef** [comment]
+1 
Looking forward to seeing this feature

**Comment by JesseStutler** [comment]
Looking forward to it! Hope to contribute

**Comment by Vacant2333** [comment]
Related issue: https://github.com/volcano-sh/volcano/issues/3731
it included the all components now

**Comment by kevin-wangzefeng** [comment]
Repository setup done at: https://github.com/volcano-sh/volcano-global
As volcano/federation was not used, there's an automatic redirect behavior to volcano-global now.

**Comment by william-wang** [comment]
The repo is ready now, close the issue.
