### ISSUE TITLE
Improve the process on create/archive repos

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/community#6]
There're several repos are in-active for a while, let's archive them or move them out of Volcano, e.g. kubesim.
And it's also better to build a process on new repo creation; currently, anyone has the related permission can create the repo with scenarios or targets.

**Comment by k82cn** [comment]
Here's the suggestion based on activities of each repos.

|  repos   | description  | suggestion
|  ----  | ----  | ----  |
| community  | Volcano community content |  as is |
| volcano  | A Kubernetes Native Batch System (Project under CNCF) |  as is |
| benchmark  | This repository aims to simulate various random scenarios to test the scheduling performance |  remove |
| federation | Cluster federation for batch workload. |  remove |
| resource-exporter | Resource Exporter for volcano scheduling, e.g. NUMA-Aware scheduling. |  merge with devices |
| apis | The API (CRD) of Volcano |  as is |
| website | Volcano website and documentation repo: https://volcano.sh |  as is |
| kubesim | A simulator of Kuberntes for batch and service workload. |  remove |
| kube-state-metrics | Add-on agent to generate and expose cluster-level metrics. |  as is |
| installer | Volcano Installation and Configuration Management | remove |
| charts | The helm charts of Volcano | remove |
| devices | Device plugins for Volcano, e.g. GPU | as is |

**Comment by Thor-wl** [comment]
I'm OK about the advice. Let's take a discussion at community meeting.

**Comment by kevin-wangzefeng** [comment]
Generally OK to me, but for repos e.g. kubesim, installer and charts, there are some code already, we can archive them instead of directly remove them?

**Comment by k82cn** [comment]
Let's move them to `volcano-retired` org, similar to https://github.com/kubernetes-retired .
Regarding kubesim, it's contributed by @suleisl2000 from openbsi; @suleisl2000, are you ok to get kubsim back or move it to volcano-retired?

**Comment by william-wang** [comment]
That's ok to me. We need to remove/archive these in-active repos from time to time. We will have a discussion on the community meeting.

**Comment by suleisl2000** [comment]
prefer to move it back to my repo, e.g. openbsi :)

**Comment by Thor-wl** [comment]
If no different voice, I'll take the advice above into practice recently.

**Comment by k82cn** [comment]
Done :)
