### ISSUE TITLE
Request to be a member of Volcano community

### ISSUE THREAD

**Issue by TaiPark** [volcano-sh/community#60]
Hello, Volcano community! Over the past few months, I have learned a great deal from the community and have made several improvements by submitting some PR. Now, I am eager to become a part of the Volcano community and contribute even more.

Here are the PR that have been merged in the Volcano community:

Volcano:
https://github.com/volcano-sh/volcano/pull/3602
https://github.com/volcano-sh/volcano/pull/3700

Volcano-Apis:
https://github.com/volcano-sh/apis/pull/132
https://github.com/volcano-sh/apis/pull/134
https://github.com/volcano-sh/apis/pull/135
https://github.com/volcano-sh/apis/pull/136

**Comment by Monokaix** [comment]
+1
Thanks for your contribution and welcome to Volcano community！

**Comment by lowang-bh** [comment]
+1

**Comment by wangyang0616** [comment]
+1
welcome to Volcano community！

**Comment by kevin-wangzefeng** [comment]
Thanks for your contribution, I just sent the invitation, you can visit https://github.com/volcano-sh to confirm and join.

**Comment by TaiPark** [comment]
Thanks! I will close this issue
