### ISSUE TITLE
Request to be a member of Volcano community

### ISSUE THREAD

**Issue by Vacant2333** [volcano-sh/community#61]
Hello, Volcano community! 

I have learned a lot from the community and participated in the open source activities of the volcano community this year. Now, I hope to become a member of the Volcano community and continue to promote the [Volcanic-Global (federation)](https://github.com/volcano-sh/federation) to make more contributions.

Volcano:
https://github.com/volcano-sh/volcano/pull/3588
https://github.com/volcano-sh/volcano/pull/3406

Federation:
https://github.com/volcano-sh/federation/pull/1
https://github.com/volcano-sh/federation/pull/2

Attented volcano issues:
[Volcano supports queue capacity management capabilities in multi-cluster AI workload scheduling](https://summer-ospp.ac.cn/org/prodetail/243ba0505?list=org&navpage=org)
[CNCF - Volcano: Volcano supports multi-cluster AI workloads scheduling (2024 Term 1)](https://mentorship.lfx.linuxfoundation.org/project/132a4971-6969-4ca6-a695-783ece3ac768)

**Comment by william-wang** [comment]
+1
thanks for your contributions!

**Comment by kevin-wangzefeng** [comment]
+1
Thanks and looking forward to more your contributions!

**Comment by kevin-wangzefeng** [comment]
Invitation sent, you can visit https://github.com/volcano-sh to accept it.

**Comment by Vacant2333** [comment]
Thanks!
