### ISSUE TITLE
Request to be a member of Volcano community

### ISSUE THREAD

**Issue by JesseStutler** [volcano-sh/community#62]
Hello, Volcano community! Over the past two months, I have learned a great deal from the community and made some contributions by submitting some PRs, and I also participated in reviewing code and collecting features, hosting volcano meetings and participating in discussions every week. I will also participate in volcano's graduation work in the future. Now, I am eager to become a member of the Volcano community and hope that I can make more contributions to volcano. 

Here are my PRs:
- merged:
https://github.com/volcano-sh/volcano/pull/3711
https://github.com/volcano-sh/volcano/pull/3727
https://github.com/volcano-sh/volcano/pull/3739
https://github.com/volcano-sh/volcano/pull/3750
https://github.com/volcano-sh/volcano/pull/3758
https://github.com/volcano-sh/volcano/pull/3817
- ongoing:
https://github.com/volcano-sh/volcano/pull/3751
https://github.com/volcano-sh/volcano/pull/3799

**Comment by william-wang** [comment]
+1, thanks for your contributions!

**Comment by Monokaix** [comment]
+1
Welcome to volcano community！

**Comment by JesseStutler** [comment]
Already joined, close the issue now.
