### ISSUE TITLE
Request to be a member of Volcano community

### ISSUE THREAD

**Issue by Wang-Kai** [volcano-sh/community#63]
Hello, Volcano community! Over the past months, I have learned a great deal from the community and made some contributions by submitting some PRs, and I also participated in reviewing code and collecting features, hosting volcano meetings and participating in discussions every week. I will also participate in volcano's graduation work in the future. Now, I am eager to become a member of the Volcano community and hope that I can make more contributions to volcano.

Here are PRs:
- merged
https://github.com/volcano-sh/volcano/pull/3599
https://github.com/volcano-sh/volcano/pull/3598
https://github.com/volcano-sh/volcano/pull/3479

- ongoing
https://github.com/volcano-sh/volcano/pull/3593
https://github.com/volcano-sh/volcano/pull/3686

**Comment by Monokaix** [comment]
+1 Thanks for your contribution！

**Comment by william-wang** [comment]
+1 
Welcome to Volcano family :)

**Comment by JesseStutler** [comment]
+1 Thanks for your contribution!

**Comment by kevin-wangzefeng** [comment]
Thanks for your application and welcome onboard!
The invitation has been sent, you can visit https://github.com/volcano-sh to accept it.

**Comment by Wang-Kai** [comment]
Already joined, close the issue now.
