### ISSUE TITLE
Request to be an Approver of Volcano community

### ISSUE THREAD

**Issue by archlitchi** [volcano-sh/community#64]
Hi teams, I'm requesting to be an approver of volcano community.

I have been involved in volcano community since 2021, and have been focused on gpu-sharing feature in volcano. I design and develop volcano-vgpu in volcano v1.9+ version, and will continue to maintain these features.

PRs I have submitted: 
volcano: [20+](https://github.com/volcano-sh/volcano/pulls?q=is%3Apr+is%3Aclosed+author%3Aarchlitchi)
volcano-device-plugin: [10+](https://github.com/volcano-sh/devices/pulls?q=is%3Apr+author%3Aarchlitchi)

PRs I reviewed: 
volcano: [8](https://github.com/volcano-sh/volcano/pulls?q=is%3Apr+reviewed-by%3Aarchlitchi)
volcano-device-plugin: [20+](https://github.com/Project-HAMi/volcano-vgpu-device-plugin/pulls)

Issues submitted: about [2](https://github.com/volcano-sh/volcano/issues?q=is%3Aissue+author%3Aarchlitchi+)

I want to be an approver of volcano community to make more contributions and promote a more prosperous volcano community. I will continue to bring more device-sharing features from other manufacturers(cambricon, hygon, mthreads,etc...) to volcano

**Comment by william-wang** [comment]
Thank you for your great contribution:)
+1

**Comment by Monokaix** [comment]
+1
Thanks for your contribution for volcano community!

**Comment by JesseStutler** [comment]
+1
Thanks for your contribution!

**Comment by hwdef** [comment]
+1
Thanks for your contribution!
