### ISSUE TITLE
Apply for member role

### ISSUE THREAD

**Issue by Tingtal** [volcano-sh/community#8]
Hi all,

I'm the translator for Volcano documentation, promotional materials, and website contents. I hope to join the Volcano community and look forward to your kind approval.

Thanks!
Tingtal Ling

**Comment by william-wang** [comment]
+1, Thanks for your contribution for Volcano.

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/volcano-sh to confirm and join.
