### ISSUE TITLE
Apply for Volcano member role

### ISSUE THREAD

**Issue by Jessica-wang-0816** [volcano-sh/community#9]
Hi all,
I'm working offline for Volcano for a long time and apply for member role now. My offline contributions are as follows:
I have worked to make Volcano more famous in the technology fields such as HPC/AI/BigData for nearly a year,and now I want to do more work about Volcano publishment correction.

**Comment by kevin-wangzefeng** [comment]
+1
Invitation sent, please visit https://github.com/volcano-sh to confirm and join.
